accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('user-list/', views.user_list),
]

egg/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
    path('sprints/', include('sprints.urls')),
    path('groups/', include('study_groups.urls')),
    path('problems/', include('problems.urls')),
    path('roles/', include('roles.urls')),
]

goals/urls.py
from django.urls import path

urlpatterns = [
    
]

roles/urls.py
from django.urls import path

urlpatterns = [
    
]

sprints/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.new),
]

study_groups/urls.py
from django.urls import path
from . import views

app_name = 'study_groups'
urlpatterns = [
    path('', views.index, name='index'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    name = models.CharField(max_length=10)
    boj_id = models.CharField(max_length=20)
    streak = models.IntegerField(default=0)

problems/models.py
from django.db import models


class Problem(models.Model):
    problem_num = models.IntegerField()
    problem_name = models.CharField(max_length=20)

roles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from study_groups.models import StudyGroup


# Create your models here.
class Role(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE)
    is_staff = models.BooleanField(default=False)

sprints/models.py
from django.db import models

# Create your models here.

study_groups/models.py
from django.db import models

# Create your models here.
class StudyGroup(models.Model):
    group_name = models.CharField(max_length=20)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = list(UserCreationForm.Meta.fields) + ['name', 'boj_id']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = '아이디'
        self.fields['name'].label = '이름'
        self.fields['boj_id'].label = '백준 아이디'
        self.fields['password1'].label = '비밀번호'
        self.fields['password2'].label = '비밀번호 확인'

        # 제약 조건 커스터마이즈
        self.fields['username'].help_text = "아이디는 150자 이하의 문자, 숫자 및 특수 문자(@/./+/-/_)만 허용됩니다."

        self.fields['password1'].help_text = "비밀번호는 적어도 8자 이상이어야 하며, 개인 정보와 유사하면 안 됩니다."
        self.fields['password2'].help_text = " "


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('name', 'email')

problems/forms.py
from django import forms
from .models import Problem


class ProblemForm(forms.ModelForm):
    class Meta:
        model = Problem
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash, get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import CustomUserCreationForm, CustomUserChangeForm
from .serializer import CustomUserSerializer
from .models import User


def login(request):
    if request.user.is_authenticated:
        return redirect('study_groups:index')
    
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('study_groups:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('study_groups:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('study_groups:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('study_groups:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def delete(request):
    request.user.delete()
    return redirect('study_groups:index')


@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('study_groups:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('study_groups:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def user_list(request):
    users = get_user_model().objects.all().values()
    print(users[0])
    # serializer = CustomUserSerializer(list(users), many=True)
    # print(">>>>>>>>>>>", serializer.data)
    return JsonResponse(users[0])

roles/views.py
from django.shortcuts import render

# Create your views here.

sprints/views.py
from django.shortcuts import render
from django.http import JsonResponse


def new(request):
    return JsonResponse

study_groups/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'study_groups/index.html')

accounts/templates/accounts/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>비밀번호 변경</h1>
  <form action="{% url 'change_password' user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>로그인 페이지</h1>
  <form action="{% url "accounts:login" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
  </form>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원가입 페이지</h1>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

accounts/templates/accounts/update.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>회원정보수정</h1>
  <form action="{% url "accounts:update" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</body>
</html>

study_groups/templates/study_groups/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>메인페이지</h1>
  {% if request.user.is_authenticated %}
    <h3>{{ user.username }}님 안녕하세요!</h3>
    <form action="{% url "accounts:logout" %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="LOGOUT">
    </form>
    <form action="{% url "accounts:delete" %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="회원탈퇴">
    </form>
    <a href="{% url "accounts:update" %}">회원정보수정</a>
  {% else %}
    <a href="{% url "accounts:login" %}">LOGIN</a>
    <a href="{% url "accounts:signup" %}">SIGNUP</a>
  {% endif %}

  <hr>



</body>
</html>